/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/phone/3D-iphone-16-scene.glb --draco 
Author: tranminhluan (https://sketchfab.com/tranminhluan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-16-pro-96be8c7e49fa4f949855db3e7f2e64e0
Title: Iphone 16 Pro
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/phone/3D-iphone-16-scene.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.phone16pro} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.phone16pro} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.phone16pro_transparent} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.phone16pro} />
    </group>
  )
}

useGLTF.preload('/phone/3D-iphone-16-scene.glb')
